### ISSUE TITLE
Add blacklist

### ISSUE THREAD

**Issue by jeremejevs** [doowb/unlazy-loader#24]
Before #23 is here, a temporary workaround could be implemented, allowing users to somehow specify the modules they don't want in the bundle.

For example, I'm using `markdown-toc` in my frontend project, and I don't need `gray-matter` (which doesn't even work in the browser, because it requires `fs`), so I could do something like this: `loader: 'unlazy?blacklist[]=gray-matter'` (or maybe scope the blacklist to certain parent modules, e.g. `blacklist[]=markdown-toc>gray-matter`).

When a blacklisted require is detected, e.g. `requires.matter = require('gray-matter')`, `require(...)` could be just replaced with `{}` or something. 

This is dirty, but should do the trick.

**Comment by jonschlinkert** [comment]
> allowing users to somehow specify the modules they don't want in the bundle.

I'm still learning about webpack, is this something that belongs in this loader, or can that be done in a different loader/plugin (e.g. single-responsibility, like you would with gulp plugins)? Or does webpack not work that way?

**Comment by doowb** [comment]
> I'm still learning about webpack

Same here and I was just about to make a similar comment.

> can that be done in a different loader

This is what I was thinking too. I think there's already a setting or loader or whatever to do `alias` in the config. Since this is designed as a loader, it should be transforming the code, then other loaders can run after it on the transformed code. I've tested this by using the `babel-loader` before this loader, so I'm assuming it'll work the other way around.

Other than `gray-matter`, is this loader working for you? Feedback on this is really helpful, so thank you for trying it out. (btw... I thought webpack would automatically replace built-in node modules like `fs` so users don't have to specifically exclude them.)

**Comment by jeremejevs** [comment]
Yeah, my line of thinking was that `unlazy-loader` should do it out of the box until the better solution is around, but I suppose you could also just recommend using it in tandem with another loader, which does what I've described above.

It can be accomplished with `null-loader` (which just truncates all files it matches), but it's too rigid (e.g. what if I load `coffee-script` in my application on-demand, but I don't want it being included in any other bundles).

Regarding `fs`, apparently yes, it's as easy as just adding this to the config:
```
node: {
  fs: 'empty',
}
```

And yes, thanks for implementing this, it does work! Even before `babel-loader`.

**Comment by doowb** [comment]
I think blacklisting is out of scope for this loader. This should be done through the config mentioned above or a different loader that is able to remove/replace modules after this one has done it's transformation.
